### ISSUE TITLE
Dev Task - Set Up Project Planning

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#1]
As a **developer**, I can **set up my project planning environments** so that I can **drive my project forwards and keep track of it's development**.

**Tasks**

- [x] Set up GitHub Projects Board
- [x] Set up local folder for PP5
- [x] Set up Figma File for wireframes
- [x] Set up Lucidchart for ERD
