### ISSUE TITLE
USER STORY - Single Product View

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#14]
As a **customer**, I can **choose an individual product** so that I can **view its description, price, colours, sizes available etc**.

**Acceptance Criteria**
- User can click on an item to view its basic information and image
- Size dropdown visible and selectable relevant to product
- Add to Bag/Add to Wishlist button visible
- Responsive to all screen sizes
- Basic review section added to template

**Tasks**

- [x] Create Product view HTML/CSS
- [x] Ensure responsive
- [x] Add relevant product size dropdown logic to applicable products
- [x] Add to Bag/Wishlist button HTML/CSS with user feedback
