### ISSUE TITLE
USER STORY - Add Products to Bag

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#15]
As a **customer**, I can **click on 'Add to Bag' in my product view **so that I can **add the product to my bag**.

**Acceptance Criteria**
- Ensure 'Add to Bag' button connects items with shopping bag
- Button is styled and responsive on all screen sizes

**Tasks**

- [x] Write bag views.py function for adding to bag
- [x] Connect HTML with backend
- [x] Check styling and responsiveness
