### ISSUE TITLE
USER STORY - Edit Bag

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#16]
As a **customer**, I can **increase/decrease/remove quantities of a product in my bag** so that I can **have control over what I wish to purchase**.

**Acceptance Criteria**
- User can see Update/Remove item quantity
- Update/Remove buttons preform as expected

**Tasks**

- [x] Add Update/Remove quantity field HTML/CSS
- [x] Add quantity_update_script.html  to 'Bag' HTML
- [x] Add update/remove logic to 'Bag' views.py 
- [x] Test
