### ISSUE TITLE
USER STORY - View Bag Total

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#17]
As a **customer**, I can **view my bag total from any page** so that I can **keep track of my potential spending**.

**Acceptance Criteria**
- Bag icon shows when no items added to bag. Bag item + quantity indicator shows when items have been added
- Bag icon is visible on main header in mobile view
- Number of items in bag displayed on bag icon

**Tasks**

- [x] bag contexts.py and views.py to connect bag items to shopping bag view
- [x] connect bag quantity to bag icon and test
- [x] calculate delivery threshold and add to settings.py
- [x] check responsiveness on all screen sizes
