### ISSUE TITLE
USER STORY - Carbon Footprint Saving

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#18]
As a **customer**, I can **view my running total of carbon saved when I add products** so that I can **see how much carbon my purchases would had saved in their production vs non eco-friendly products of the same type**.

**Acceptance Criteria**
- Carbon Footprint saved and carbon total display for user before and after checkout
- Totals respond to quantity change in bag

**Tasks**

- [x] Add carbon totals logic to bag contexts
- [x] Ensure bag tools loaded on all checkout pages
- [x] Call carbon totals to be displayed on style information card for customer to see
