### ISSUE TITLE
USER STORY - Carbon Footprint Saving - Checkout View

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#19]
As a **customer**, I can **view my total carbon footprint saving on checkout and it's associated climate impact/lifestyle changes** so that I can **understand the equivalent value of carbon saved versus purchasing the same non eco-friendly products**.

**Acceptance Criteria**
- User Can view running carbon total during shopping
- User can view total carbon values in checkout success/order confirmation view

**Tasks**

- [x] Add carbon logic to bag contexts to pull data from Product models
- [x] Style carbon total display section
- [x] Add grand total carbon values fields to Order models and add calculations to checkout view to save total values for display in order confirmation/history
