### ISSUE TITLE
Dev Task - Development Environment Setup

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#2]
As a **developer**, I can **setup my project development environment** so that I can **start my project, install all dependencies and begin documentation**.

**Tasks**

- [x] Setup GitHub repo using CI Full Template 
- [x] Connect repo with Projects board
- [x] Ensure .gitignore file available
- [x] Install Django
- [x] Setup settings.py
- [x] Migrate changes
- [x] Create project superuser
- [x] Install and setup allAuth and templates
- [x] Freeze requirements
