### ISSUE TITLE
USER STORY - Order Confirmation Email

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#21]
As a **customer**, I can **receive an email after purchasing** so that I can **confirm my purchase and keep a record of my order**.

**Acceptance Criteria**
- Email received by user with correct order information

**Tasks**

- [x] Setup email in settings.py
- [x] Create email template forms to display order information
- [x] Create checkout success views
- [x] Test
