### ISSUE TITLE
USER STORY - Edit Product Inventory

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#23]
As a**site admin**, I can **edit existing inventory from a frontend form** so I can **change the quantity of stock, sizes, colours or edit products description, price or image**.

- Only authorised users, 'admin/superuser' may see the 'edit' button
- Edit button present for each item
- Edit button brings Admin to 'Edit Product' form
- Form saves with product added

**Tasks**

- [x] Edit button added to product detail page
- [x] Edit form created and accessible via Admin Dashboard
- [x] Edit views added to product views to process the form and its saving
