### ISSUE TITLE
USER STORY - Delete Product from Inventory

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#24]
As a **site admin**, I can **delete product from the inventory using a frontend form** so that I can **remove it from sale**.

**Acceptance Criteria**
- Only authorised users, 'admin/superuser' may see the 'delete' button
- Delete button present for each item
- Delete button removes item when clicked

**Tasks**

- [x] Delete button added to product detail page
- [x] Delete views added to product views to process deletion

**Comment by amylour** [comment]
Could Have Tasks

- [ ] 'Admin Mode' activated once admin uses Admin Dashboard to alter inventory, this way the 'edit/delete' buttons only visible when in 'Admin Mode' and not always present when admin may be shopping. 'Admin Mode' exited by button in Admin Dashboard
- [ ] Create 'Delete Confirmation' modal to ensure no accidental deletions of products
