### ISSUE TITLE
USER STORY - Contact Us

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#25]
As a **customer**, I can **use the Contact Us form** so I can **send a message to the business/site admin**.

**Acceptance Criteria**
- Contact form linked in footer successfully
- Contact Form modal appears on click
- Contact Form is submitted successfully

**Tasks**

- [x] Create Contact modal & form
- [x] Connect contact form using contexts.py
- [x] Test Connection of contact form to website email account
