### ISSUE TITLE
USER STORY - Newsletter Form SignUp

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#26]
As a **customer**, I can **enter my details into the newsletter form** so I can **receive emails about products or environmental issues/climate saving tips**.

**Acceptance Criteria**
- Newsletter sign up is visible in footer
- User can submit email for information newsletter to their inbox

**Tasks**

- [x] Create newsletter input form
- [x] Style input form
- [x] Test form submission to receive email

**Comment by amylour** [comment]
-Newsletter setup using MailChimp account
