### ISSUE TITLE
USER STORY - User Login

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#27]
As a **site user**, I can **enter my login details** so that I can **login in to my account**.

**Acceptance Criteria**
- User Account icon visible
- Clicking login option brings user to Login page
- User status is displayed over Account icon and Logout option shown

**Tasks**

- [x] Add Account icon and dropdown menu to header
- [x] Connect AllAuth templates and views to the login function
- [x] Add styling to Account icon to display user status
