### ISSUE TITLE
USER STORY - Footer links

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#28]
As a **site user **, I can **click on the visible links in the footer** so that I can **view the relevant information and destinations**.

**Acceptance Criteria**
- Footer items are visible to user
- Footer links are clickable and bring user to correct location
- Footer is responsive

**Tasks**

- [x] Update footer html with active links
- [x] Create linked page html
- [x] Test footer links
