### ISSUE TITLE
Dev Task - Prepare Product Images

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#29]
As a **developer**, I can **prepare my media files** so that they are **the best file size and format** for my website.

**Acceptance Criteria**
- Files are in PNG format where possible
- File sizes are kept below 1MB
- Best quality images used
- Images credits and copyrights recorded in README

**Tasks**

- [x] Find suitable image files for products
- [x] Convert to PNG and resize
- [x] Record all image credits and copyrights
