### ISSUE TITLE
USER STORY - Home Page Structure

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#3]
As a **customer**, I can **view the site's home page** so that I can **understand the site's intentions and purpose**.

**Acceptance Criteria**
- User can view the home page when website loads
- Home page navigation area and footer are visible
- Business details are displayed

**Tasks**

- [x] Create base.html
- [x] Connect base.html to index.html
- [x] Provide basic information, formatting and styling to the page
- [x] Add favicon
- [x] Add header/footer html

**Comment by amylour** [comment]
Added to home page section structure and more styling.
