### ISSUE TITLE
Dev Task - Add Products to DB

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#30]
As a **developer** I can **create a Category and Product model** so that I can **add products for the store to my database.**

**Acceptance Criteria**
- Products added to database
- Products visible on website product view page 

**Tasks**

- [x] Create Category and Product models in Product app models.py
- [x] Migrate changes
- [x] Update database with products
- [x] Connect products to product view page
