### ISSUE TITLE
USER STORY - Product Category Filtering

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#31]
As a **site user**, I can **click on a navbar item for a specific category** so that I can **choose to view a smaller amount of related products**.

**Acceptance Criteria**
- Navbar items visible and provide feedback on hover/click
- Navbar item brings user to specific category of products when clicked
- Navbar item has styling to indicate which category the user is viewing in an 'active' state

**Tasks**

- [x] Connect nav items to correct urls and category names
- [x] Style active class nav items in bold to indicate to the user where they are on the site
- [x] Test correct products presented
