### ISSUE TITLE
USER STORY - Toasts/User Notifications

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#34]
As a **customer** I can **receive visual communication/feedback as I use the store** so that I can **confirm my actions and choices.**

**Acceptance Criteria**
- Users are informed when they add, edit or remove an item from their bag.
- Message displays to user on all screen sizes
- Users may dismiss the message container using the 'x' to close
- Checkout link displayed brings users to the checkout page
- Users are informed if they need to increase their spend to avail of free delivery

**Tasks**

- [x] Set up message container HTML/CSS
- [x] Connect bag view to display contents to user when item added/edited/removed
- [x] Link to checkout page
