### ISSUE TITLE
DEV TASK - Deployment to Heroku and AWS Setup

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#36]
As a **developer**, I can **deploy my project to Heroku and setup file storage on AWS** so that I can **host my project on reliable services for users to be able to access and use the live site**.

**Acceptance Criteria**
- 'everneed' is viewable as 'everneed.herokuapp.com'
- Project static files are hosted on AWS and retrievable to the live site

**Tasks**

- [x] Create Procfile and set DEBUG to False for deployment
- [x] Setup Heroku and environment variables for Stripe
- [x] Setup AWS Bucket and connect to Heroku
