### ISSUE TITLE
USER STORY -  Edit Wishlist

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#38]
As a **logged-in user** I can **click the 'Remove' icon beside my Wishlist item** so that I can **remove that product from my Wishlist**.

**Acceptance Criteria**
- User can see 'Remove' icon beside Wishlist product.
- Clicking the 'Remove' icon removes item from the Wishlist

**Tasks**

- [x] Create 'Remove from Wishlist' function in views
- [x] Add Remove icon and connect function
- [x] Test and check for user feedback
