### ISSUE TITLE
USER STORY - Site Navigation

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#4]
As a **customer**, I can **see and use the navigation bar** so that I can **make my way around the site and get to where I would like**.

**Acceptance Criteria**
- Navigation bar is visible and responsive to screen sizes
- Logo is present and returns user to home page
- Navigation options are clickable and display which page the user is on
- Links bring user to the correct area
- Search field is visible in navbar
- Footer displays additional navigational qualities as well as business information

**Tasks**

- [x] Create header.html
- [x] Create footer.html
- [x] Update base.html
- [x] Update nav links with destinations
- [x] Check responsiveness
- [x] Add search field to navbar
