### ISSUE TITLE
USER STORY - Email Validation for Account 

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#40]
As a **site user**, I can **register my email and receive a validation link via email** so that I can **create an account with everneed to track my spending and purchases**.

**Acceptance Criteria**
- User registers
- User receives email and email link allows validation
- Validation succeeds and allows user to log in successfully

**Tasks**

- [x] Set up Gmail account for sending emails
- [x] Set up App Password and connect to Heroku and settings.py
- [x] Add Development variables for Email authentication 
- [x] Test
