### ISSUE TITLE
DEV TASK - Manual Testing

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#41]
As a**developer**, I can **thoroughly test all aspects of my project** so that I can **make sure the user has the correct experience and receives no errors or dead ends.**

**Acceptance Criteria**
- TESTING.md is written up to include every feature and aspect of project
- All features work as expected

**Tasks**

- [x] Test all input and validation
- [x] Validate all HMTL, CSS, JS and Python
- [x] Write up TESTING.md with screenshots
