### ISSUE TITLE
USER STORY - Discount Codes

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#43]
As a **customer** I can **enter a discount code, given to me via email from Everneed** so that I can **redeem a discount on my purchases**.

**Acceptance Criteria**
- Customer receives discount code through email newsletter from Everneed, if they are subscribed to the newsletter
- Customer is made aware of current discount by on window load modal/toast if they sign up to the newsletter
- Generated discount code input field in shopping bag accepts discount and reduces grand total
- Discount code may only be used once

**Tasks**

- [ ] Setup discount redemption field and logic
- [ ] Create discount modal on screen load
- [ ] Generate newsletter for discount code redemption
