### ISSUE TITLE
USER STORY - Search Function

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#5]
As a **customer**, I can **enter text into the search bar** so that I can **search for a specific item**.

**Acceptance Criteria**
- Search bar is visible in navigation area
- Placeholder text in the search field informs the user to enter text
- Search function brings user to the correct item searched

**Tasks**

- [x]  Add search bar to navigation area
- [x]  Adjust default bootstrap styling
- [x]  Add search functionality to view.py
- [x] Test search bar
