### ISSUE TITLE
USER STORY - All Products View

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#6]
As a **customer**, I can **click on all products view** so that I can **view all the products available to me**.

**Acceptance Criteria**
- Link to view all products visible in dropdown menu
- User clicks to access all products view

**Tasks**

- [x]  Product database
- [x]  Product models.py
- [x]  View products views.py
- [x]  Products HTML/CSS

**Comment by amylour** [comment]
- 'Sort By:' HTML/CSS and logic added and tested 
- User input feedback styled to reflect website design
