### ISSUE TITLE
USER STORY - Create & Manage Account

### ISSUE THREAD

**Issue by amylour** [amylour/everneed#7]
As a **customer** I can **create and manage an account with everneed** so that I can **keep my personal details, order history and speed up my checkout process**.

**Acceptance Criteria**
- User can click on 'Account' icon to Register or Log In
- User is given feedback via Account icon in header changing to acknowledge user is logged in or logged out
- User can add, save, and view their delivery details on the Account page
- User's details auto-filled into checkout fields for purchases
- Order History viewable

**Tasks**

- [x] Create user authentication pages
- [x] Connect user profile/account with checkout logic to save user's delivery details and orders
- [x] Account allows editing and saving of details from account page 
- [x] User feedback implemented for log in, log out and account update
